config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/haddocking/haddock3:
      branch: main
      repo: https://github.com/haddocking/haddock3
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/haddocking/haddock3 git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-seashell-beetle.sh
        container: qc.acc_leaky-mauve-hound
  QC.Doc:
    repos:
      github.com/haddocking/haddock3 find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-russet-gopher.sh
        container: qc.doc_bluesy-cardinal-fowl
      github.com/haddocking/haddock3 git:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-brown-moorhen.sh
        container: qc.doc_muzzy-bistre-mist
      github.com/haddocking/haddock3 markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-burgundy-grouse.sh
        container: qc.doc_chummy-amaranth-chimpanzee
      github.com/haddocking/haddock3 restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-linen-jellyfish.sh
        container: qc.doc_hasty-brass-terrier
  QC.Lic:
    repos:
      github.com/haddocking/haddock3 licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-taupe-quokka.sh
        container: qc.lic_homey-copper-grouse
  QC.Sec:
    repos:
      github.com/haddocking/haddock3 bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-silver-crane.sh
        container: qc.sec_surly-plum-mau
  QC.Sty:
    repos:
      github.com/haddocking/haddock3 flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-alizarin-moth.sh
        container: qc.sty_flimsy-xanthic-angelfish
      github.com/haddocking/haddock3 jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-amber-lemming.sh
        container: qc.sty_baggy-peach-havanese
  QC.Ver:
    repos:
      github.com/haddocking/haddock3 get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-purple-birman.sh
        container: qc.ver_whiny-beige-donkey
timeout: 5400
